-- auto-session --> snacks dashboard --done
-- bookmarks-nvim --> nothing
-- codecompanion.local --> nothing
-- codecompanion --> nothing
-- conform-nvim --> nothing
-- coverage-nvim --> nothing
-- csvview-nvim --> nothing
-- diffview-nvim --> remove
-- git-blame --> none
-- harpoon --> remove
-- init -->
-- lazygit --> snacks.lazygit
-- lualine --> mini.statusline
-- neotest-python --> keep
-- neotest --> keep
-- noice --> mini notify
-- nvim-dap-python --> keep
-- nvim-dap-ui --> keep
-- nvim-dap --> keep
-- nvim-lint --> keep
-- python-venv --> keep
-- reminders-nvim --> remove
-- render-markdown --> keep
-- scratch-nvim --> snacks scratch
-- snacks-gh --> keep
-- snacks -->
-- task-decomposer --> keep
-- toggleterm --> snacks.terminal
-- trouble-nvim --> keep
-- health -->
-- autopairs --> mini.pairs
-- debug - keep
-- gitsigns --> mini.git
-- indent_line --> snacks.indent
-- lint keep
-- neo-tree --> mini.files
-- telescope - fzf-lua
